global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80

  metrics:
    address: :8082

metrics:
  prometheus:
    entryPoint: metrics
################################################################
# API and dashboard configuration
################################################################

#
api:
  insecure: true
  dashboard: true


providers:
   # Enable the file provider to define routers / middlewares / services in file
   file:
      filename: digital-bank.yaml

accessLog:
  filePath:
